# Generated by Django 4.0.6 on 2022-07-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
    ]
